//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.AnotherTestProject
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Invoice item.
    /// </summary>
    // *** Start programmer edit section *** (InvoiceItem CustomAttributes)

    // *** End programmer edit section *** (InvoiceItem CustomAttributes)
    [AutoAltered()]
    [Caption("Товарная позиция")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("InvoiceItemE", new string[] {
            "Amount as \'Количество\'",
            "Product as \'Товар\'",
            "Product.Name as \'Название товара\'"}, Hidden=new string[] {
            "Product.Name"})]
    [MasterViewDefineAttribute("InvoiceItemE", "Product", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class InvoiceItem : ICSSoft.STORMNET.DataObject
    {
        
        private int fAmount;
        
        private IIS.AnotherTestProject.Product fProduct;
        
        private IIS.AnotherTestProject.Invoice fInvoice;
        
        // *** Start programmer edit section *** (InvoiceItem CustomMembers)

        // *** End programmer edit section *** (InvoiceItem CustomMembers)

        
        /// <summary>
        /// Amount.
        /// </summary>
        // *** Start programmer edit section *** (InvoiceItem.Amount CustomAttributes)

        // *** End programmer edit section *** (InvoiceItem.Amount CustomAttributes)
        public virtual int Amount
        {
            get
            {
                // *** Start programmer edit section *** (InvoiceItem.Amount Get start)

                // *** End programmer edit section *** (InvoiceItem.Amount Get start)
                int result = this.fAmount;
                // *** Start programmer edit section *** (InvoiceItem.Amount Get end)

                // *** End programmer edit section *** (InvoiceItem.Amount Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InvoiceItem.Amount Set start)

                // *** End programmer edit section *** (InvoiceItem.Amount Set start)
                this.fAmount = value;
                // *** Start programmer edit section *** (InvoiceItem.Amount Set end)

                // *** End programmer edit section *** (InvoiceItem.Amount Set end)
            }
        }
        
        /// <summary>
        /// Invoice item.
        /// </summary>
        // *** Start programmer edit section *** (InvoiceItem.Product CustomAttributes)

        // *** End programmer edit section *** (InvoiceItem.Product CustomAttributes)
        [PropertyStorage(new string[] {
                "Product"})]
        [NotNull()]
        public virtual IIS.AnotherTestProject.Product Product
        {
            get
            {
                // *** Start programmer edit section *** (InvoiceItem.Product Get start)

                // *** End programmer edit section *** (InvoiceItem.Product Get start)
                IIS.AnotherTestProject.Product result = this.fProduct;
                // *** Start programmer edit section *** (InvoiceItem.Product Get end)

                // *** End programmer edit section *** (InvoiceItem.Product Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InvoiceItem.Product Set start)

                // *** End programmer edit section *** (InvoiceItem.Product Set start)
                this.fProduct = value;
                // *** Start programmer edit section *** (InvoiceItem.Product Set end)

                // *** End programmer edit section *** (InvoiceItem.Product Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.AnotherTestProject.Invoice.
        /// </summary>
        // *** Start programmer edit section *** (InvoiceItem.Invoice CustomAttributes)

        // *** End programmer edit section *** (InvoiceItem.Invoice CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Invoice"})]
        public virtual IIS.AnotherTestProject.Invoice Invoice
        {
            get
            {
                // *** Start programmer edit section *** (InvoiceItem.Invoice Get start)

                // *** End programmer edit section *** (InvoiceItem.Invoice Get start)
                IIS.AnotherTestProject.Invoice result = this.fInvoice;
                // *** Start programmer edit section *** (InvoiceItem.Invoice Get end)

                // *** End programmer edit section *** (InvoiceItem.Invoice Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InvoiceItem.Invoice Set start)

                // *** End programmer edit section *** (InvoiceItem.Invoice Set start)
                this.fInvoice = value;
                // *** Start programmer edit section *** (InvoiceItem.Invoice Set end)

                // *** End programmer edit section *** (InvoiceItem.Invoice Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "InvoiceItemE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View InvoiceItemE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("InvoiceItemE", typeof(IIS.AnotherTestProject.InvoiceItem));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of InvoiceItem.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfInvoiceItem CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfInvoiceItem CustomAttributes)
    public class DetailArrayOfInvoiceItem : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.AnotherTestProject.DetailArrayOfInvoiceItem members)

        // *** End programmer edit section *** (IIS.AnotherTestProject.DetailArrayOfInvoiceItem members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type InvoiceItem by index.
        /// </summary>
        /// <summary>
        /// Adds object with type InvoiceItem.
        /// </summary>
        public DetailArrayOfInvoiceItem(IIS.AnotherTestProject.Invoice fInvoice) : 
                base(typeof(InvoiceItem), ((ICSSoft.STORMNET.DataObject)(fInvoice)))
        {
        }
        
        public IIS.AnotherTestProject.InvoiceItem this[int index]
        {
            get
            {
                return ((IIS.AnotherTestProject.InvoiceItem)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.AnotherTestProject.InvoiceItem dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
