//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.AnotherTestProject
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Invoice.
    /// </summary>
    // *** Start programmer edit section *** (Invoice CustomAttributes)

    // *** End programmer edit section *** (Invoice CustomAttributes)
    [AutoAltered()]
    [Caption("Накладная")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("InvoiceE", new string[] {
            "SaleDate as \'Sale date\'",
            "Client as \'Client\'",
            "Client.Name as \'Name\'"}, Hidden=new string[] {
            "Client.Name"})]
    [AssociatedDetailViewAttribute("InvoiceE", "InvoiceItem", "InvoiceItemE", true, "", "Invoice item", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("InvoiceE", "Client", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("InvoiceL", new string[] {
            "SaleDate as \'Sale date\'",
            "Client.Name as \'Name\'"})]
    public class Invoice : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fSaleDate;
        
        private IIS.AnotherTestProject.Client fClient;
        
        private IIS.AnotherTestProject.DetailArrayOfInvoiceItem fInvoiceItem;
        
        // *** Start programmer edit section *** (Invoice CustomMembers)

        // *** End programmer edit section *** (Invoice CustomMembers)

        
        /// <summary>
        /// SaleDate.
        /// </summary>
        // *** Start programmer edit section *** (Invoice.SaleDate CustomAttributes)

        // *** End programmer edit section *** (Invoice.SaleDate CustomAttributes)
        public virtual System.DateTime SaleDate
        {
            get
            {
                // *** Start programmer edit section *** (Invoice.SaleDate Get start)

                // *** End programmer edit section *** (Invoice.SaleDate Get start)
                System.DateTime result = this.fSaleDate;
                // *** Start programmer edit section *** (Invoice.SaleDate Get end)

                // *** End programmer edit section *** (Invoice.SaleDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Invoice.SaleDate Set start)

                // *** End programmer edit section *** (Invoice.SaleDate Set start)
                this.fSaleDate = value;
                // *** Start programmer edit section *** (Invoice.SaleDate Set end)

                // *** End programmer edit section *** (Invoice.SaleDate Set end)
            }
        }
        
        /// <summary>
        /// Invoice.
        /// </summary>
        // *** Start programmer edit section *** (Invoice.Client CustomAttributes)

        // *** End programmer edit section *** (Invoice.Client CustomAttributes)
        [PropertyStorage(new string[] {
                "Client"})]
        [NotNull()]
        public virtual IIS.AnotherTestProject.Client Client
        {
            get
            {
                // *** Start programmer edit section *** (Invoice.Client Get start)

                // *** End programmer edit section *** (Invoice.Client Get start)
                IIS.AnotherTestProject.Client result = this.fClient;
                // *** Start programmer edit section *** (Invoice.Client Get end)

                // *** End programmer edit section *** (Invoice.Client Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Invoice.Client Set start)

                // *** End programmer edit section *** (Invoice.Client Set start)
                this.fClient = value;
                // *** Start programmer edit section *** (Invoice.Client Set end)

                // *** End programmer edit section *** (Invoice.Client Set end)
            }
        }
        
        /// <summary>
        /// Invoice.
        /// </summary>
        // *** Start programmer edit section *** (Invoice.InvoiceItem CustomAttributes)

        // *** End programmer edit section *** (Invoice.InvoiceItem CustomAttributes)
        public virtual IIS.AnotherTestProject.DetailArrayOfInvoiceItem InvoiceItem
        {
            get
            {
                // *** Start programmer edit section *** (Invoice.InvoiceItem Get start)

                // *** End programmer edit section *** (Invoice.InvoiceItem Get start)
                if ((this.fInvoiceItem == null))
                {
                    this.fInvoiceItem = new IIS.AnotherTestProject.DetailArrayOfInvoiceItem(this);
                }
                IIS.AnotherTestProject.DetailArrayOfInvoiceItem result = this.fInvoiceItem;
                // *** Start programmer edit section *** (Invoice.InvoiceItem Get end)

                // *** End programmer edit section *** (Invoice.InvoiceItem Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Invoice.InvoiceItem Set start)

                // *** End programmer edit section *** (Invoice.InvoiceItem Set start)
                this.fInvoiceItem = value;
                // *** Start programmer edit section *** (Invoice.InvoiceItem Set end)

                // *** End programmer edit section *** (Invoice.InvoiceItem Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "InvoiceE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View InvoiceE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("InvoiceE", typeof(IIS.AnotherTestProject.Invoice));
                }
            }
            
            /// <summary>
            /// "InvoiceL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View InvoiceL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("InvoiceL", typeof(IIS.AnotherTestProject.Invoice));
                }
            }
        }
    }
}
